### ISSUE TITLE
Thanks 

### ISSUE THREAD

**Issue by Pawansingh333** [Solana0x/GrassNode2#1]
Thanks for your bot IM using 100 paid proxy and every proxy connected but Grass Balance showing zero why and how to check balance please reply 
![Uploading Screenshot (7).png…]()

**Comment by Pawansingh333** [comment]
![Screenshot (6)](https://github.com/user-attachments/assets/9610ed8c-55b7-4f3e-8bdc-010b342f597a)

**Comment by Pawansingh333** [comment]
![Uploading Screenshot (7).png…]()

**Comment by surendra841** [comment]
you probably using rotational proxies

**Comment by Solana0x** [comment]
it will take ~2 days for points to credit depending on your country time normal points are added around 11AM UTC next day !! 

So wait until that and make sure to use proper and quality residential proxies along with 24/7 uptime of script
